WayfireWM/wf-shell

- src/panel/widgets/clock.cpp
GDateTime uses month 1-12 while GCalender uses 0-11.
Thanks to gimpnixon for pointing out the problem.
> clock: Fix calender month

- config.h.in
- meson.build
- meson_options.txt
- src/panel/meson.build
- src/panel/panel.cpp
This makes building gvc and volume widget optional which is needed
to build wf-shell without pulseaudio dependency.
> Make pulse dependency optional

- meson.build
- src/util/wf-shell-app.cpp
This adds a check for a file at the location
$sysconfdir/wayfire/wf-shell-defaults.ini which can be used
to override defaults set in the metadata files.
> Add path for default options file

- src/panel/widgets/volume.cpp
- src/panel/widgets/volume.hpp
This happens when output is unplugged or when widget is unloaded.
> volume: disconnect all signal handlers when destroying widget

- src/panel/widgets/launchers.cpp
- src/panel/widgets/launchers.hpp
I've started working on panel launchers: custom labels on launchers from cmd+icon combo
Fixes #6
> Add custom labels on launchers from cmd+icon combo

- src/panel/widgets/volume.cpp
This was causing wf-panel to crash i.e. when hotplugging outputs.
> volume: Don't use object after unref

- src/util/wf-shell-app.cpp
Part 3 of https://github.com/WayfireWM/wayfire/issues/493.
The API was changed to accomodate loading metadata from a search
path.  That's not relevant to wf-shell (yet), so just pass a
single-element vector.
> wf-shell-app: use vector for build_configuration

- src/meson.build
This is necessary to allow wcm to look up wf-shell's metadata and
sysconf directories, to initialize wf-shell's configuration.
> src/meson.build: generate wf-shell.pc

- meson.build
This allows for installing wf-shell into a prefix other than
Wayfire's, while preserving the original behaviour by default.
> meson.build use own configuration directories

- proto/wayfire-shell-unstable-v2.xml
Renaming protocol name to `wayfire_shell_unstable_v2` fixed the include issue of qtwaylandscanner.
> Fixed issues generating client header using qtwaylandscanner

- .gitmodules
- meson.build
- metadata/panel.xml
- src/panel/widgets/menu.cpp
- src/panel/widgets/menu.hpp
The button runs the command from the config key panel/menu_logout_command.
> panel menu: Add logout button

- meson.build
- meson_options.txt
If a packager has packaged wayland-logout separately, the
wayland-logout subproject will cause wf-shell to conflict.
> build: Make wayland-logout installation optional

- metadata/dock.xml
- metadata/panel.xml
- src/dock/dock.cpp
- src/panel/panel.cpp
- src/util/gtk-utils.cpp
- src/util/gtk-utils.hpp
This pull request adds `panel/css_path` and `dock/css_path` into the configuration file schema, allowing for custom CSS loading of both the panel and the dock.
```ini
[panel]
css_path = /path/to.css
[dock]
css_path = /path/to.css
```
I think the code to load those CSS could've been better placed elsewhere, but I really can't be bothered to set up my editor environment again, so I would kindly ask you the maintainers to do that, as you know the project more than I do.
> Add {panel,dock}/css_path and custom CSS support

- metadata/panel.xml
- src/panel/widgets/network.cpp
- src/panel/widgets/network.hpp
This option allows a user to define a custom onclick command for the network widget so commands like `terminal -e nmtui` or others can be used in place of having a static dependency on gnome-control-center.
> Added custom onclick command support to network widget.

- src/panel/widgets/volume.cpp
During startup, the volume icon is shown as "muted", no matter whether the volume is really at 0 or at maximum value. The problem seems to be that volume_scale.get_target_value() returns the current value, not the desired one.
This patch fixes this by adding a new method that returns the set value instead of the current one. Tried to return in get_target_value() the final value instead of the current one, but breaks changing the volume.
> Fix volume icon muted at startup

- src/panel/widgets/menu.cpp
Gtk3 has a bug which causes flickering tooltips when hovering over
menu items in the menu. Don't set tooltips to avoid this bug.
> menu: Omit buggy code

- metadata/panel.xml
- src/panel/widgets/menu.cpp
- src/panel/widgets/menu.hpp
When a user clicks the logout button in the menu and no command is set,
open a default logout interface.
> panel: Implement default logout user interface

- metadata/dock.xml
- metadata/panel.xml
- src/panel/meson.build
- src/panel/panel.cpp
- src/panel/widgets/notifications/daemon.cpp
- src/panel/widgets/notifications/daemon.hpp
- src/panel/widgets/notifications/notification-center.cpp
- src/panel/widgets/notifications/notification-center.hpp
- src/panel/widgets/notifications/notification-info.cpp
- src/panel/widgets/notifications/notification-info.hpp
- src/panel/widgets/notifications/single-notification.cpp
- src/panel/widgets/notifications/single-notification.hpp
- wf-shell.ini.example
This PR adds notifications center widget for wf-panel. I'm opening the PR before it's fully ready because it requires much of code review, as well as some help with improvements such as config options.
> Notifications widget

- src/panel/widgets/battery.cpp
- src/panel/widgets/window-list/toplevel.cpp
Adds spacing between icons and labels in `battery` and `window-list` widgets
> Space between icon and label

- src/panel/widgets/tray/item.cpp
- src/panel/widgets/tray/item.hpp
- src/util/gtk-utils.cpp
- src/util/gtk-utils.hpp
`IconThemePath` is `libappindicator`'s non-standardized property of `StatusNotifierItem`. In particular, it's used by Steam, so I think it should be supported by `wf-panel`'s implementation of SNI as well.
> tray: support IconThemePath property

- metadata/panel.xml
- src/panel/meson.build
- src/panel/panel.cpp
- src/panel/widgets/command-output.cpp
- src/panel/widgets/command-output.hpp
> "Command output" widgets

- metadata/panel.xml
- src/panel/widgets/notifications/notification-center.cpp
- src/panel/widgets/notifications/notification-center.hpp
- src/panel/widgets/volume.cpp
- src/panel/widgets/volume.hpp
- src/util/gtk-utils.cpp
- src/util/gtk-utils.hpp
- Adds icon size option for `volume` and `notifications` widgets
- Changes `battery_icon_size`'s default value to `32`
- Adds missing `*_icon_size`'s min value
> icon size option for volume and notifications

- src/panel/widgets/tray/watcher.cpp
> sni: use `service` value according to the specs

- src/panel/widgets/volume.cpp
It's a very annoying thing because changing the list of widgets in `wmc` makes panel capture the focus.
> volume: don't show-and-hide popover on init

- src/panel/widgets/clock.cpp
Fixes #135 
Currently `clock` widget is always placed at right regardless of its position in config file (e.g. `battery clock` or `clock battery` produces the same result). IMHO, this behavior seems weird.
> clock: use pack_start to be placed correctly between other widgets

- src/panel/panel.cpp
- src/panel/widgets/notifications/daemon.cpp
- src/panel/widgets/notifications/daemon.hpp
- src/panel/widgets/notifications/notification-center.cpp
- src/panel/widgets/notifications/notification-center.hpp
- src/panel/widgets/notifications/single-notification.cpp
Fixes an awful mistake: `Daemon` was a namespace instead of singleton. 
Fixes that notifications center disappears after widgets reloading.
> Notifications: make daemon a singleton

- meson.build
- src/util/wf-autohide-window.cpp
This PR fixes the problem when the menu or another popover has been opened, it grabs keyboard focus, and then if you click outside of wf-panel, the popover should close, but it doesn't.
With this PR, everything should work (but also needs some Wayfire fixes to be found in https://github.com/WayfireWM/wayfire/pull/1913).
> fix popover hiding

- src/util/wf-autohide-window.cpp
- src/util/wf-autohide-window.hpp
Commit 6652635 fixed autohide issues when `zwf_shell_manager_v2` isn't available, but changed, as a side effect, the behaviour of the window's `auto_exclusive_zone`, causing an unnecessary dependency on the `zwf_shell_manager_v2` for the exclusive zone as well, affecting wf-panel when the compositor's wayfire-shell plugin is disabled (see issue #198 for details).
Fix it by refactoring the `WayfireAutohidingWindow` class, dividing some methods charged with too much roles (i.e the
`WayfireAutohidingWindow::set_autoexclusive_zone()`), transfering constructor code into new methods, introducing some new logic controls both in the class body and in the callbacks.
To ensure everything is working fine, I did several tests on both `wf-panel` and `wf-deck` to check the behavior under different …
> Fix excusive zone when `zwf_shell_manager_v2` is unavailable

- proto/wayfire-shell-unstable-v2.xml
- src/panel/panel.cpp
- src/panel/widgets/menu.cpp
- src/panel/widgets/menu.hpp
- src/util/wf-autohide-window.cpp
- src/util/wf-autohide-window.hpp
- src/util/wf-shell-app.cpp
- src/util/wf-shell-app.hpp
Update wayfire-shell protocol and listen for the toggle_menu event. Fixes #11 because ipc plugin can be used to allow calling toggle_menu from a script.
Requires [wayfire PR 2097](https://github.com/WayfireWM/wayfire/pull/2097).
> Listen for toggle_menu event

- src/background/background.cpp
Fixes #203 
I used a separate assignment to avoid compiler warnings.
Note that things still won't work if the user specifies a directory with parentheses, but there will be no crash only an error message. Single image filenames with parentheses work.
> Fix crash with parentheses in filenames

- metadata/background.xml.in
- src/background/background.cpp
- src/background/background.hpp
This adds two minor features to wf-background:
- The ability to set the fade duration (including to zero).
- The ability to update/cycle the background by sending SIGHUP.
Together, these can be allowed to implement seamless background
updates of slow-moving scenes. As an example, my background is an
image recalculated by xplanet every few minutes. I run xplanet
with a post_command that sends a SIGHUP to wf-background.
With a fade duration of zero, wf-background just replaces the
image imperceptibly, with no fading and no flicker.
> wf-background: allow seamless background updates

- src/panel/widgets/window-list/toplevel.cpp
- src/panel/widgets/window-list/window-list.cpp
Set the scrolled window policy to NEVER instead of AUTOMATIC to allow it to become smaller than 32 pixels in height.
> window-list: Allow smaller panel heights

- metadata/background.xml.in
- src/background/background.cpp
- src/background/background.hpp
- wf-shell.ini.example
I felt strongly about https://github.com/WayfireWM/wf-shell/pull/58 so I replicated the fork against master and followed the requested changes.
After some testing with a variety of images and screens I made further edits:
- Added an `image_scale` value that gets passed into the render logic for each image
- Added cairo context save/restore and placed a scale inside it to allow the image to be scaled up in-place without loading it a second time.
These were necessary as loading tall images in ultrawide screens or visa-versa caused a crash from attempting to create a Pixbuf that was too large.
I have attempted to stick to the coding style of the project but feel free to correct me on it.
> Add "Fill and Crop" option for wf-background. Pt 2

- .github/workflows/ci.yaml
- src/panel/widgets/window-list/toplevel.cpp
The icons in the window list are loaded by parsing the desktop files for a few variations of the window's app ID in a few known locations.
Add /.local/share/applications to the list of locations it looks in, to ensure that apps installed in the user's home directory are considered as well.
> window-list: use ~/.local/share when looking for apps / icons

- src/panel/widgets/launchers.cpp
Chasing around a missing icon in launcher lead me to make this patch:
- Setting a launcher icon/cmd pair would load the image from an absolute path
- Setting a `.desktop` launcher would work if the icon was a themed icon name
- Setting a `.desktop` with an icon that has an absolute path would only attempt to look it up via theme
I did a quick sanity check here https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html :
> Icon to display in file manager, menus, etc. If the name is an absolute path, the given file will be used. If the name is not...
So I've put in a check for character at index 0 being `/` and load it from file.
While not in scope for this PR, it is worth asking if the icon/cmd pair could/should be patched to also allow loading by icon-theme-name if it …
> Check for and load absolute path icons in panel launchers

- metadata/panel.xml
- src/panel/widgets/launchers.cpp
- src/panel/widgets/menu.cpp
- src/panel/widgets/menu.hpp
- wf-shell.ini.example
Options added:
- Application icons in list form `panel/menu_list`
- Menu shows application categories `panel/menu_show_categories`
- Categories width `panel/menu_min_category_width`
New Menu Features:
- Categories to the left of application list
- Keyboard navigation of applications & categories
- Right click an application to choose between alternative actions
- Changing search term selects first item in list
- Categories hidden if no applications exist for it
Commits include work done for a different PR merged here and then reverted as the patch was unrelated.
> Collection of Menu alterations

- src/util/gtk-utils.cpp
gtk-utils: set_image_icon use both theme and filesystem
gtk-utils: set_image_icon stores at double necessary scale to allow unblurred scaling
> gtk-utils: set icon changes

- src/panel/widgets/tray/item.cpp
- src/panel/widgets/tray/item.hpp
tray: add icons to button
tray: fix click logic for button
tray: attach popup menu to button
> tray: allow css styling

- src/panel/widgets/notifications/daemon.cpp
- src/panel/widgets/notifications/notification-info.cpp
- src/panel/widgets/notifications/single-notification.cpp
> Fix & refactor notifications
